name: greate_places
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.11
  path: ^1.8.1
  image_picker: ^0.8.5
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6+1
  google_fonts: ^3.0.1
  sqflite: ^2.0.3+1
  location: ^4.4.0
  geocoding: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  flutter_launcher_icons: "^0.10.0"
  mobx_codegen: ^2.0.7

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.jpeg"


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  
